name: Spark Word Count CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: sparkdemo
          POSTGRES_USER: postgres
          POSTGRES_DB: wordcount
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install types-psycopg2 pandas-stubs
    
    - name: Lint with flake8
      run: |
        flake8 src tests
    
    - name: Check formatting with black
      run: |
        black --check src tests
    
    - name: Check imports with isort
      run: |
        isort --check-only --profile black src tests
    
    - name: Type check with mypy
      run: |
        mypy src
    
    - name: Test with pytest
      run: |
        pytest tests/unit
      env:
        DB_HOST: localhost
        DB_USER: postgres
        DB_PASSWORD: sparkdemo
        DB_NAME: wordcount
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      if: success()
      with:
        fail_ci_if_error: false 